#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name=" _ATTENDANCE")]
public partial class AttendanceDataContextDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public AttendanceDataContextDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AttendanceDB"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public AttendanceDataContextDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AttendanceDataContextDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AttendanceDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AttendanceDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.WEB_PROC_INSERT_ATTENDANCE")]
	public int WEB_PROC_INSERT_ATTENDANCE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIN", DbType="VarChar(50)")] string pIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CHECKTIME", DbType="DateTime")] System.Nullable<System.DateTime> cHECKTIME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CREATED_BY", DbType="VarChar(50)")] string cREATED_BY)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pIN, cHECKTIME, cREATED_BY);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.WEB_PROC_GET_ATTENDANCE_RECORD")]
	public ISingleResult<WEB_PROC_GET_ATTENDANCE_RECORDResult> WEB_PROC_GET_ATTENDANCE_RECORD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIN", DbType="VarChar(50)")] string pIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATEFROM", DbType="VarChar(10)")] string dATEFROM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATETO", DbType="VarChar(10)")] string dATETO)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pIN, dATEFROM, dATETO);
		return ((ISingleResult<WEB_PROC_GET_ATTENDANCE_RECORDResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.WEB_PROC_GET_SUBORDINATES")]
	public ISingleResult<WEB_PROC_GET_SUBORDINATESResult> WEB_PROC_GET_SUBORDINATES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIN", DbType="VarChar(10)")] string pIN)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pIN);
		return ((ISingleResult<WEB_PROC_GET_SUBORDINATESResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CHANGE_PASSWORD")]
	public int CHANGE_PASSWORD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="VarChar(50)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIN", DbType="VarChar(50)")] string pIN)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pASSWORD, pIN);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.WEB_PROC_LOGIN")]
	public ISingleResult<WEB_PROC_LOGINResult> WEB_PROC_LOGIN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIN", DbType="VarChar(50)")] string pIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="VarChar(50)")] string pASSWORD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pIN, pASSWORD);
		return ((ISingleResult<WEB_PROC_LOGINResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.WEB_PROC_GET_PASSWORD")]
	public ISingleResult<WEB_PROC_GET_PASSWORDResult> WEB_PROC_GET_PASSWORD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIN", DbType="VarChar(50)")] string pIN)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pIN);
		return ((ISingleResult<WEB_PROC_GET_PASSWORDResult>)(result.ReturnValue));
	}
}

public partial class WEB_PROC_GET_ATTENDANCE_RECORDResult
{
	
	private System.Nullable<int> _PIN;
	
	private string _NAME;
	
	private System.Nullable<System.DateTime> _DATE;
	
	private System.Nullable<System.TimeSpan> _TIMEIN;
	
	private System.Nullable<System.TimeSpan> _TIMEOUT;
	
	public WEB_PROC_GET_ATTENDANCE_RECORDResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="Int")]
	public System.Nullable<int> PIN
	{
		get
		{
			return this._PIN;
		}
		set
		{
			if ((this._PIN != value))
			{
				this._PIN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(150)")]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
	public System.Nullable<System.DateTime> DATE
	{
		get
		{
			return this._DATE;
		}
		set
		{
			if ((this._DATE != value))
			{
				this._DATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEIN", DbType="Time")]
	public System.Nullable<System.TimeSpan> TIMEIN
	{
		get
		{
			return this._TIMEIN;
		}
		set
		{
			if ((this._TIMEIN != value))
			{
				this._TIMEIN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEOUT", DbType="Time")]
	public System.Nullable<System.TimeSpan> TIMEOUT
	{
		get
		{
			return this._TIMEOUT;
		}
		set
		{
			if ((this._TIMEOUT != value))
			{
				this._TIMEOUT = value;
			}
		}
	}
}

public partial class WEB_PROC_GET_SUBORDINATESResult
{
	
	private System.Nullable<int> _PIN;
	
	private string _NAME;
	
	public WEB_PROC_GET_SUBORDINATESResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="Int")]
	public System.Nullable<int> PIN
	{
		get
		{
			return this._PIN;
		}
		set
		{
			if ((this._PIN != value))
			{
				this._PIN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(150)")]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
}

public partial class WEB_PROC_LOGINResult
{
	
	private System.Nullable<int> _PIN;
	
	private string _NAME;
	
	private string _CNIC;
	
	private string _DEPARTMENT_ABBV;
	
	private string _USER_TYPE;
	
	public WEB_PROC_LOGINResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="Int")]
	public System.Nullable<int> PIN
	{
		get
		{
			return this._PIN;
		}
		set
		{
			if ((this._PIN != value))
			{
				this._PIN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(150)")]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNIC", DbType="VarChar(50)")]
	public string CNIC
	{
		get
		{
			return this._CNIC;
		}
		set
		{
			if ((this._CNIC != value))
			{
				this._CNIC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT_ABBV", DbType="VarChar(50)")]
	public string DEPARTMENT_ABBV
	{
		get
		{
			return this._DEPARTMENT_ABBV;
		}
		set
		{
			if ((this._DEPARTMENT_ABBV != value))
			{
				this._DEPARTMENT_ABBV = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_TYPE", DbType="VarChar(50)")]
	public string USER_TYPE
	{
		get
		{
			return this._USER_TYPE;
		}
		set
		{
			if ((this._USER_TYPE != value))
			{
				this._USER_TYPE = value;
			}
		}
	}
}

public partial class WEB_PROC_GET_PASSWORDResult
{
	
	private System.Nullable<int> _PIN;
	
	private string _PASSWORD;
	
	public WEB_PROC_GET_PASSWORDResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="Int")]
	public System.Nullable<int> PIN
	{
		get
		{
			return this._PIN;
		}
		set
		{
			if ((this._PIN != value))
			{
				this._PIN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50)")]
	public string PASSWORD
	{
		get
		{
			return this._PASSWORD;
		}
		set
		{
			if ((this._PASSWORD != value))
			{
				this._PASSWORD = value;
			}
		}
	}
}
#pragma warning restore 1591
